#开发环境
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
     mongo:
       caches:
         -
           cacheName: cache1
           collectionName: collection1
           flushOnBoot: true
           ttl: 2592000
         -
           cacheName: cache2
           collectionName: collection2
           flushOnBoot: true
           ttl: 604800



