#开发环境
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 5
      max-active: 10
      query-timeout: 1000
      druid.query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filter-class-names: stat
      filters: stat,config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
     mongo:
       database: cache_database
       caches:
         -
           cacheName: cache1
           collectionName: collection1
           flushOnBoot: true
           ttl: 2592000
         -
           cacheName: cache2
           collectionName: collection2
           flushOnBoot: true
           ttl: 604800



